/*
Add Port use for Sewing Machine
*/
INSERT INTO Port (ID, Name)
SELECT 1, "USB"
WHERE NOT EXISTS (SELECT 1 FROM Port WHERE Name = "USB");

INSERT INTO Port (ID, Name)
SELECT 2, "Tastatur"
WHERE NOT EXISTS (SELECT 1 FROM Port WHERE Name = "Tastatur");

INSERT INTO Port (ID, Name)
SELECT 3, "Com1"
WHERE NOT EXISTS (SELECT 1 FROM Port WHERE Name = "Com1");

INSERT INTO Port (ID, Name)
SELECT 4, "Com2"
WHERE NOT EXISTS (SELECT 1 FROM Port WHERE Name = "Com2");

INSERT INTO Port (ID, Name)
SELECT 5, "Com3"
WHERE NOT EXISTS (SELECT 1 FROM Port WHERE Name = "Com3");

INSERT INTO Port (ID, Name)
SELECT 6, "Com4"
WHERE NOT EXISTS (SELECT 1 FROM Port WHERE Name = "Com4");

INSERT INTO Port (ID, Name)
SELECT 7, "Com5"
WHERE NOT EXISTS (SELECT 1 FROM Port WHERE Name = "Com5");

INSERT INTO Port (ID, Name)
SELECT 8, "Com5"
WHERE NOT EXISTS (SELECT 1 FROM Port WHERE Name = "Com5");

INSERT INTO Port (ID, Name)
SELECT 9, "Com6"
WHERE NOT EXISTS (SELECT 1 FROM Port WHERE Name = "Com6");

INSERT INTO Port (ID, Name)
SELECT 10, "Com7"
WHERE NOT EXISTS (SELECT 1 FROM Port WHERE Name = "Com7");

INSERT INTO Port (ID, Name)
SELECT 11, "Com8"
WHERE NOT EXISTS (SELECT 1 FROM Port WHERE Name = "Com8");

INSERT INTO Port (ID, Name)
SELECT 12, "Com9"
WHERE NOT EXISTS (SELECT 1 FROM Port WHERE Name = "Com9");

INSERT INTO Port (ID, Name)
SELECT 13, "Com10"
WHERE NOT EXISTS (SELECT 1 FROM Port WHERE Name = "Com10");

INSERT INTO Port (ID, Name)
SELECT 14, "Com11"
WHERE NOT EXISTS (SELECT 1 FROM Port WHERE Name = "Com11");

INSERT INTO Port (ID, Name)
SELECT 15, "Com13"
WHERE NOT EXISTS (SELECT 1 FROM Port WHERE Name = "Com13");

INSERT INTO Port (ID, Name)
SELECT 16, "Com14"
WHERE NOT EXISTS (SELECT 1 FROM Port WHERE Name = "Com14");

INSERT INTO Port (ID, Name)
SELECT 17, "Com15"
WHERE NOT EXISTS (SELECT 1 FROM Port WHERE Name = "Com15");

INSERT INTO Port (ID, Name)
SELECT 18, "Com16"
WHERE NOT EXISTS (SELECT 1 FROM Port WHERE Name = "Com16");

INSERT INTO Port (ID, Name)
SELECT 19, "Com17"
WHERE NOT EXISTS (SELECT 1 FROM Port WHERE Name = "Com17");

INSERT INTO Port (ID, Name)
SELECT 20, "Com18"
WHERE NOT EXISTS (SELECT 1 FROM Port WHERE Name = "Com18");

INSERT INTO Port (ID, Name)
SELECT 21, "Com19"
WHERE NOT EXISTS (SELECT 1 FROM Port WHERE Name = "Com19");

INSERT INTO Port (ID, Name)
SELECT 22, "Com20"
WHERE NOT EXISTS (SELECT 1 FROM Port WHERE Name = "Com20");